sudo: required

language: bash

compiler:
    - gcc

services:
  - docker

before_install:
    - docker build -t exoter/rock:14.04 -f os-dockerfile .

install:
    - docker build --build-arg BUILD_MODULE="base" -t exoter/rock:14.04 -f rock-dockerfile .
    - docker build --build-arg BUILD_MODULE="tools" -t exoter/rock:14.04 -f rock-dockerfile .
    - docker build --build-arg BUILD_MODULE="gui" -t exoter/rock:14.04 -f rock-dockerfile .

notifications:
    email:
        - havyhidalgo@gmail.com
