sudo: required

language: bash

compiler:
    - gcc

services:
  - docker

before_install:
    #- docker build -t exoter/rock:14.04 -f os-dockerfile .

install:
    - docker build -t exoter/rock:14.04 -f rock-dockerfile --build-arg=BUILD_MODULE="base" .

notifications:
    email:
        - havyhidalgo@gmail.com
